---
apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-1
  annotations:
    argocd.argoproj.io/hook: PostSync
  namespace: myworkload
spec:
  template:
    spec:
      containers:
        - name: config
          image: quay.io/openshift/origin-cli:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -eo pipefail
              set -x
              
              oc get Secret -n openshift-gitops

      restartPolicy: Never
      serviceAccountName: default
  backoffLimit: 1
